name: pipeline
on:   
  push:
    branches:    
      - main
  pull_request:
    branches:    
      - main

jobs:    
  validate:
    runs-on: ubuntu-latest
    name: test pipeline
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      
      - run: python --version