name: pipeline
on:   
  push:
    branches:    
      - main
  pull_request:
    branches:    
      - main

jobs:    
  validate:
    runs-on: ubuntu-latest
    name: test pipeline
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      
      - name: python version
        run: python --version

      - name: installing morph-kgc
        run: pip install morph-kgc
      
      - name: running morph-kgc
        run: python3 -m morph_kgc config.ini