name: pipeline
on:   
  pull_request:
    branches:    
      - main

jobs:    
  validate:
    runs-on: ubuntu-latest
    name: action-morphkgc
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      
      - name: python version
        run: python --version

      - name: installing morph-kgc
        run: pip install morph-kgc

      - name: action-morphkgc
        uses: ./
        id: 'action-morphkgc'
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }} 
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: ls

      - run: ls ./morphkgc/

      - run: cat ./morphkgc/config.ini
      
      #- name: running morph-kgc
      #  run: python3 -m morph_kgc ./morphkgc/config.ini